"""empty message

Revision ID: 26645435d1a0
Revises: 5ae1ca3a4b1e
Create Date: 2021-03-08 15:33:22.515528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26645435d1a0'
down_revision = '5ae1ca3a4b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('streak_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'streak_start')
    # ### end Alembic commands ###
