"""empty message

Revision ID: 2a99363b4a86
Revises: 620401e0472b
Create Date: 2021-03-08 15:50:16.519530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a99363b4a86'
down_revision = '620401e0472b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('policy_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'policy_approved')
    # ### end Alembic commands ###
