"""empty message

Revision ID: 5ae1ca3a4b1e
Revises: 
Create Date: 2021-03-08 15:28:25.850640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae1ca3a4b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('contribution_points', sa.Integer(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('reputation_confidence', sa.Integer(), nullable=True),
    sa.Column('streak_length', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('policy_description', sa.String(length=200), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('current_mask_level', sa.Integer(), nullable=True),
    sa.Column('current_busyness_level', sa.Integer(), nullable=True),
    sa.Column('last_computed', sa.DateTime(), nullable=True),
    sa.Column('average_mask_level', sa.Integer(), nullable=True),
    sa.Column('average_busyness_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('covid_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('estimated_start', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('mask_level', sa.Integer(), nullable=True),
    sa.Column('busyness_level', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('policy_followed', sa.Integer(), nullable=True),
    sa.Column('policy_comment', sa.String(length=200), nullable=True),
    sa.Column('review_rating', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_report')
    op.drop_table('location_log')
    op.drop_table('covid_reports')
    op.drop_table('location')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
