"""empty message

Revision ID: 620401e0472b
Revises: 26645435d1a0
Create Date: 2021-03-08 15:42:58.184659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620401e0472b'
down_revision = '26645435d1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_report', sa.Column('policy_comment_approved', sa.Boolean(), nullable=True))
    op.add_column('user_report', sa.Column('review_comment_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_report', 'review_comment_approved')
    op.drop_column('user_report', 'policy_comment_approved')
    # ### end Alembic commands ###
